### ISSUE TITLE
EACCES: Permission denied on /AppData/Local/Temp/

### ISSUE THREAD

**Issue by tal5ab** [Cimpress-MCP/vagrant-winrm-syncedfolders#3]
Hi
I am trying to use this plugin to connect to AWS windows instance , to sync the folders with minimal files to transfer (including the chef cookbooks etc)
To avoid installing rsync on the local machine ...

but for some reason i am getting this error , no matter if my cmd was run as administrator or not:
Is it a local machine permission or on the remote machine?

Here is the full output after the winrm connection was established:

DEBUG winrmshell: initializing WinRMShell
DEBUG winrmshell: powershell executing:
hostname
if ($?) { exit 0 } else { if($LASTEXITCODE) { exit $LASTEXITCODE } else { exit 1 } }
 INFO winrmshell: Attempting to connect to WinRM...
 INFO winrmshell:   - Host: 52.89.77.83
 INFO winrmshell:   - Port: 5985
 INFO winrmshell:   - Username: vagrant
 INFO winrmshell:   - Transport: plaintext
DEBUG winrmshell: Output: {:data=>[{:stdout=>"WIN-APQMU2J37AC"}, {:stdout=>"\r\n"}], :exitcode=>0}
 INFO winrm: WinRM is ready!
 INFO run_instance: Time for SSH ready: 277.7978160381317
 INFO interface: info: Machine is booted and ready for use!
 INFO interface: info: ==> default: Machine is booted and ready for use!
==> default: Machine is booted and ready for use!
 INFO warden: Calling IN action: #<Proc:0x4ad4530@C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.
7.4/lib/vagrant/action/warden.rb:94 (lambda)>
 INFO warden: Calling OUT action: #<Proc:0x4ad4530@C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1
.7.4/lib/vagrant/action/warden.rb:94 (lambda)>
 INFO warden: Calling OUT action: #VagrantPlugins::AWS::Action::RunInstance:0x4a9f9e8
 INFO warden: Calling OUT action: #VagrantPlugins::AWS::Action::ElbRegisterInstance:0x4a4d7a0
 INFO warden: Calling OUT action: #VagrantPlugins::AWS::Action::WarnNetworks:0x4a4d7b8
 INFO synced_folders: Invoking synced folder enable: winrm
 INFO interface: info: Uploading with WinRM: C:/DevOps/test_AWS => /vagrant
 INFO interface: info: ==> default: Uploading with WinRM: C:/DevOps/test_AWS => /vagrant
==> default: Uploading with WinRM: C:/DevOps/test_AWS => /vagrant
DEBUG winrm: Attempting WinRM upload attempt number 1
 INFO winrm: Uploading: C:/DevOps/test_AWS to /vagrant
 INFO retryable: Retryable exception raised: #<Errno::EACCES: Permission denied - (C:/Users/TABRAMSO
/AppData/Local/Temp/winrm_upload20150917-11356-vha13f.zip20150917-11356-hiufj6, C:/Users/TABRAMSO/Ap
pData/Local/Temp/winrm_upload20150917-11356-vha13f.zip)>
DEBUG winrm: Attempting WinRM upload attempt number 1
 INFO winrm: Uploading: C:/DevOps/test_AWS to /vagrant
 INFO retryable: Retryable exception raised: #<Errno::EACCES: Permission denied - (C:/Users/TABRAMSO
/AppData/Local/Temp/winrm_upload20150917-11356-1peexqw.zip20150917-11356-1wps3um, C:/Users/TABRAMSO/
AppData/Local/Temp/winrm_upload20150917-11356-1peexqw.zip)>
DEBUG winrm: Attempting WinRM upload attempt number 1
 INFO winrm: Uploading: C:/DevOps/test_AWS to /vagrant
ERROR warden: Error occurred: Permission denied - (C:/Users/TABRAMSO/AppData/Local/Temp/winrm_upload
20150917-11356-1lv4rpl.zip20150917-11356-z1ciss, C:/Users/TABRAMSO/AppData/Local/Temp/winrm_upload20
150917-11356-1lv4rpl.zip)
 INFO warden: Beginning recovery process...
 INFO warden: Calling recover: #VagrantPlugins::AWS::Action::RunInstance:0x4a9f9e8
 INFO machine: Calling action: read_state on provider AWS (i-56dbb98d)
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: machine_action_read_state #Vagrant::Action::Builder:0x2aeb5c0
 INFO warden: Calling IN action: #Vagrant::Action::Builtin::ConfigValidate:0x2b0c5f0
 INFO warden: Calling IN action: #VagrantPlugins::AWS::Action::ConnectAWS:0x2b0c428
 INFO connect_aws: Connecting to AWS...
 INFO warden: Calling IN action: #VagrantPlugins::AWS::Action::ReadState:0x34d0f88
 INFO warden: Calling OUT action: #VagrantPlugins::AWS::Action::ReadState:0x34d0f88
 INFO warden: Calling OUT action: #VagrantPlugins::AWS::Action::ConnectAWS:0x2b0c428
 INFO warden: Calling OUT action: #Vagrant::Action::Builtin::ConfigValidate:0x2b0c5f0
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: machine_action_up #Vagrant::Action::Builder:0x3a99d28
 INFO warden: Calling IN action: #Vagrant::Action::Builtin::Call:0x3ad1348
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: machine_action_up #Vagrant::Action::Builder:0x3bbbcc0
 INFO warden: Calling IN action: #Vagrant::Action::Builtin::DestroyConfirm:0x3bc2638
 INFO warden: Calling OUT action: #Vagrant::Action::Builtin::DestroyConfirm:0x3bc2638
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: machine_action_up #Vagrant::Action::Warden:0x3c2be78
 INFO warden: Calling IN action: #<Proc:0x48dd298@C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.
7.4/lib/vagrant/action/warden.rb:94 (lambda)>
 INFO warden: Calling IN action: #Vagrant::Action::Builtin::ConfigValidate:0x3c2bd10
 INFO warden: Calling IN action: #Vagrant::Action::Builtin::Call:0x3c2bcb0
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: machine_action_up #Vagrant::Action::Builder:0x4a4f330
 INFO warden: Calling IN action: #VagrantPlugins::AWS::Action::IsCreated:0x4a65b78
 INFO machine: Calling action: read_state on provider AWS (i-56dbb98d)
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: machine_action_read_state #Vagrant::Action::Builder:0x4a9cc28
 INFO warden: Calling IN action: #Vagrant::Action::Builtin::ConfigValidate:0x4aa6078
 INFO warden: Calling IN action: #VagrantPlugins::AWS::Action::ConnectAWS:0x4aa6060
 INFO connect_aws: Connecting to AWS...
 INFO warden: Calling IN action: #VagrantPlugins::AWS::Action::ReadState:0x4add188
 INFO warden: Calling OUT action: #VagrantPlugins::AWS::Action::ReadState:0x4add188
 INFO warden: Calling OUT action: #VagrantPlugins::AWS::Action::ConnectAWS:0x4aa6060
 INFO warden: Calling OUT action: #Vagrant::Action::Builtin::ConfigValidate:0x4aa6078
 INFO warden: Calling OUT action: #VagrantPlugins::AWS::Action::IsCreated:0x4a65b78
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: machine_action_up #Vagrant::Action::Warden:0x4bef8e0
 INFO warden: Calling IN action: #<Proc:0x357fe88@C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.
7.4/lib/vagrant/action/warden.rb:94 (lambda)>
 INFO warden: Calling IN action: #VagrantPlugins::AWS::Action::ConnectAWS:0x4bef880
 INFO connect_aws: Connecting to AWS...
 INFO warden: Calling IN action: #VagrantPlugins::AWS::Action::ElbDeregisterInstance:0x4c1d120
 INFO warden: Calling IN action: #VagrantPlugins::AWS::Action::TerminateInstance:0x4c57620
 INFO interface: info: Terminating the instance...
 INFO interface: info: ==> default: Terminating the instance...
==> default: Terminating the instance...
 INFO machine: New machine ID: nil
 INFO warden: Calling IN action: #Vagrant::Action::Builtin::ProvisionerCleanup:0x2848338
 INFO warden: Calling IN action: #<Proc:0x2b347f0@C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.
7.4/lib/vagrant/action/warden.rb:94 (lambda)>
 INFO warden: Calling IN action: #<Proc:0x3c2bc38@C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.
7.4/lib/vagrant/action/warden.rb:94 (lambda)>
 INFO warden: Calling OUT action: #<Proc:0x3c2bc38@C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1
.7.4/lib/vagrant/action/warden.rb:94 (lambda)>
 INFO warden: Calling OUT action: #<Proc:0x2b347f0@C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1
.7.4/lib/vagrant/action/warden.rb:94 (lambda)>
 INFO interface: info: Running cleanup tasks for 'chef_solo' provisioner...
 INFO interface: info: ==> default: Running cleanup tasks for 'chef_solo' provisioner...
==> default: Running cleanup tasks for 'chef_solo' provisioner...
 INFO warden: Calling OUT action: #Vagrant::Action::Builtin::ProvisionerCleanup:0x2848338
 INFO warden: Calling OUT action: #VagrantPlugins::AWS::Action::TerminateInstance:0x4c57620
 INFO warden: Calling OUT action: #VagrantPlugins::AWS::Action::ElbDeregisterInstance:0x4c1d120
 INFO warden: Calling OUT action: #VagrantPlugins::AWS::Action::ConnectAWS:0x4bef880
 INFO warden: Calling OUT action: #<Proc:0x357fe88@C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1
.7.4/lib/vagrant/action/warden.rb:94 (lambda)>
 INFO warden: Calling OUT action: #Vagrant::Action::Builtin::Call:0x3c2bcb0
 INFO warden: Calling OUT action: #Vagrant::Action::Builtin::ConfigValidate:0x3c2bd10
 INFO warden: Calling OUT action: #<Proc:0x48dd298@C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1
.7.4/lib/vagrant/action/warden.rb:94 (lambda)>
 INFO warden: Calling OUT action: #Vagrant::Action::Builtin::Call:0x3ad1348
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: Permission denied - (C:/Users/TABRAMSO/AppData/Local/Temp/winrm_upload
20150917-11356-1lv4rpl.zip20150917-11356-z1ciss, C:/Users/TABRAMSO/AppData/Local/Temp/winrm_upload20
150917-11356-1lv4rpl.zip)
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: Permission denied - (C:/Users/TABRAMSO/AppData/Local/Temp/winrm_upload
20150917-11356-1lv4rpl.zip20150917-11356-z1ciss, C:/Users/TABRAMSO/AppData/Local/Temp/winrm_upload20
150917-11356-1lv4rpl.zip)
 INFO warden: Beginning recovery process...
 INFO warden: Calling recover: #Vagrant::Action::Builtin::Call:0x3670920
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO environment: Released process lock: machine-action-08d0caea4973d67024aa1df2ecf9e1de
 INFO environment: Running hook: environment_unload
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: environment_unload #Vagrant::Action::Builder:0x3bb3de8
C:/HashiCorp/Vagrant/embedded/gems/gems/rubyzip-1.1.7/lib/zip/file.rb:416:in `rename': Permission de
nied - (C:/Users/TABRAMSO/AppData/Local/Temp/winrm_upload20150917-11356-1lv4rpl.zip20150917-11356-z1
ciss, C:/Users/TABRAMSO/AppData/Local/Temp/winrm_upload20150917-11356-1lv4rpl.zip) (Errno::EACCES)
        from C:/HashiCorp/Vagrant/embedded/gems/gems/rubyzip-1.1.7/lib/zip/file.rb:416:in`on_success_replace'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/rubyzip-1.1.7/lib/zip/file.rb:308:in `commit'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/rubyzip-1.1.7/lib/zip/file.rb:332:in`close'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/winrm-fs-0.2.0/lib/winrm-fs/core/temp_zip_file.rb:143:in `close'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/winrm-fs-0.2.0/lib/winrm-fs/core/temp_zip_file.rb:139:in`build'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/winrm-fs-0.2.0/lib/winrm-fs/core/temp_zip_file.rb:58:in `build'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/winrm-fs-0.2.0/lib/winrm-fs/core/upload_orchestrator.rb:113:in`create_temp_zip_file'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/winrm-fs-0.2.0/lib/winrm-fs/core/upload_orchestrator.rb:78:in `with_local_zip'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/winrm-fs-0.2.0/lib/winrm-fs/core/upload_orchestrator.rb:46:in`upload_directory'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/winrm-fs-0.2.0/lib/winrm-fs/file_manager.rb:113:in `upload'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/communicators/winrm/shell.rb:70:in`upload'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/communicators/winrm/communicator.rb:163:in `upload'
        from C:/Users/TABRAMSO/.vagrant.d/gems/gems/vagrant-winrm-syncedfolders-0.1.0/lib/vagrant-winrm-syncedfolders/synced_folder.rb:35:in`block (3 levels) in enable'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/retryable.rb:17:in `retryable'
        from C:/Users/TABRAMSO/.vagrant.d/gems/gems/vagrant-winrm-syncedfolders-0.1.0/lib/vagrant-winrm-syncedfolders/synced_folder.rb:33:in`block (2 levels) in enable'
        from C:/Users/TABRAMSO/.vagrant.d/gems/gems/vagrant-winrm-syncedfolders-0.1.0/lib/vagrant-winrm-syncedfolders/synced_folder.rb:28:in `tap'
        from C:/Users/TABRAMSO/.vagrant.d/gems/gems/vagrant-winrm-syncedfolders-0.1.0/lib/vagrant-winrm-syncedfolders/synced_folder.rb:28:in`block in enable'
        from C:/Users/TABRAMSO/.vagrant.d/gems/gems/vagrant-winrm-syncedfolders-0.1.0/lib/vagrant-winrm-syncedfolders/synced_folder.rb:23:in `each'
        from C:/Users/TABRAMSO/.vagrant.d/gems/gems/vagrant-winrm-syncedfolders-0.1.0/lib/vagrant-winrm-syncedfolders/synced_folder.rb:23:in`enable'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/synced_folders.rb:92:in `block in call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/synced_folders.rb:89:in`each'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/synced_folders.rb:89:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in`call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/provision.rb:80:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in`call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in`call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in`call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in`busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/call.rb:53:in`call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Users/TABRAMSO/.vagrant.d/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action/connect_aws.rb:43:in`call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/config_validate.rb:25:in`call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/handle_box.rb:56:in`call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in`call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in`busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:214:in`action_raw'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:191:in `block in action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:516:in`lock'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:178:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:178:in`action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in`call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'

i have 
    config.vm.communicator = :winrm
    config.vm.synced_folder ".", "/vagrant", type: "winrm"

And
        chef.synced_folder_type = "winrm" 

in the vagrantfile

Any help would be appreciated

Regards
Tal

**Comment by maclennann** [comment]
Hi @tal5ab, thanks for the report!

This looks like it's actually a bug in the `winrm-fs` gem that Vagrant 1.7.4 uses to perform the upload. [This GH issue](https://github.com/WinRb/winrm-fs/issues/16) seems to be the relevant one.

This has already been fixed in `winrm-fs` 0.2.1, but the version bundled with Vagrant is 0.2.0. Luckily, the version range in [vagrant's gemspec](https://github.com/mitchellh/vagrant/blob/v1.7.4/vagrant.gemspec#L32) allows us to install the newest version of this dependency on top of the embedded version and use that instead.

So, in the short term, you should be able to fix this by running `vagrant plugin install winrm-fs --plugin-version 0.2.1` (or 0.2.2 which is the current latest) which will install the new version of the gem as kind of a fake plugin into `%VAGRANT_HOME%\gems\gems` - then vagrant will begin using that version instead.

A more-complete fix would be to ask Vagrant to rebundle the 1.7.4 installer with the newer gem (which seems incredibly unlikely).

We might also be able to add `winrm-fs ~> 0.2.1` as a dependency of `vagrant-winrm-syncedfolders` so you'll get it automatically on plugin install. The only issue with that is that it will break our compatibility with vagrant 1.7.2 since `winrm-fs` requires a newer version of `winrm` than is allowed by 1.7.2. I assume 1.7.4 compatibility is more important than 1.7.2, though.

But maybe there's another solution I'm missing here that someone more familiar with vagrant plugins would know about. @chrisbaldauf what are your thoughts on this? Ditto @tknerr since the compatibility issue would cascade up (down?) to VMS.

**Comment by tal5ab** [comment]
Thank you so much
I managed to get pass the issue with 0.2.1 installed
